theme: jekyll-theme-cayman
title: Jeak Framework
url: jeakfrw.github.io
exclude:
  - .idea/
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - '*.iml'
github:
  is_project_page: true
  repository_url: https://github.com/jeakfrw/core-framework
google_analytics: "UA-142064115-1"