theme: jekyll-theme-cayman
title: Jeak Framework
url: jeakfrw.github.io
google_analytics: UA-142064115-1
exclude:
  - .idea/
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - '*.iml'
github:
  is_project_page: true
  repository_url: https://github.com/jeakfrw/jeak-framework
downloads:
  tar_url: "https://nexus.fearnixx.de/repository/jeakbot-dist/jeakbot-1.0.0.tar.gz"
  #zip_url: "https://nexus.fearnixx.de/repository/jeakbot-dist/jeakbot-1.0.0-rc.5.zip"
